name: "redis"
services:
  redis:
    image: "11notes/redis:7.4.2"
    container_name: "redis"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TZ: "Europe/Zurich"
    command:
      - SET mykey1 myvalue1 NX
      - SET mykey2 myvalue2 NX
    ports:
      - "6379:6379/tcp"
    volumes:
      - "redis.etc:/redis/etc"
      - "redis.var:/redis/var"
    restart: always

volumes:
  redis.etc:
  redis.var: