services:
  redis:
    image: "11notes/redis:7.4.0"
    container_name: "redis"
    environment:
      REDIS_PASSWORD: GreenHorsesRunLikeCheese
      TZ: Europe/Zurich
    ports:
      - "6379:6379/tcp"
    volumes:
      - "etc:/redis/etc"
      - "var:/redis/var"
    networks:
      - redis
    restart: always
volumes:
  etc:
  var:
networks:
  redis:
    driver: bridge
    internal: true