apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include (printf "%s.fullname" .Chart.Name) . }}
  labels:
    {{- include (printf "%s.labels" .Chart.Name) . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include (printf "%s.selectorLabels" .Chart.Name) . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include (printf "%s.selectorLabels" .Chart.Name) . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: pvc-copy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          args: 
            - "--pvc-copy-etc"
          volumeMounts:
            - name: etc
              mountPath: /pvc/etc
          securityContext:
            runAsUser: 0
        - name: chown
          image: "11notes/k8s-init"
          command:
            - sh
            - -c
            - |
              eleven k8s chown /redis {{ .Values.containerSecurityContext.runAsUser | default 1000 }} {{ .Values.containerSecurityContext.runAsGroup | default 1000 }}
          volumeMounts:
            - name: etc
              mountPath: /redis/etc
            - name: var
              mountPath: /redis/var
          securityContext:
            runAsUser: 0
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: REDIS_IP
              value: {{ .Values.redis.ip | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis.secretName" . }}
                  key: {{ include "redis.secretKey" . }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: etc
              mountPath: /redis/etc
            - name: var
              mountPath: /redis/var
            - name: run
              mountPath: /run
      volumes:
        {{- range $vol, $cfg := $.Values.persistence }}
        - name: {{ $vol }}
          {{- if $cfg.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "redis.claimName" (list $ $vol) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        - name: run
          emptyDir:
            medium: Memory
            {{- with .Values.tmpfs.tmp.sizeLimit }}
            sizeLimit: {{ . }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
