{{- range $vol, $cfg := $.Values.persistence }}
{{- if not $cfg.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis.fullname" $ }}-{{ $vol }}
  labels:
    {{- include "redis.labels" $ | nindent 4 }}
spec:
  accessModes:
    {{- range $cfg.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if $cfg.storageClass }}
  storageClassName: {{ $cfg.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ $cfg.size }}
---
{{- end }}
{{- end }}